-- AlterTable
ALTER TABLE "History" ADD COLUMN     "maxDecimalPlaces" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ProblemAttempt" ALTER COLUMN "answer" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "userAnswer" SET DATA TYPE DOUBLE PRECISION;
